### ISSUE TITLE
App tries to login on initial load and gets a 401.

### ISSUE THREAD

**Issue by tckastanek** [thinkful-c11/devcupid#20]
Just need to reconfigure the logic to only attempt login on GitHub Login link. Should still reroute 'onboarding/intro' if user is already authorized.

**Comment by wilm42** [comment]
Working on this

**Comment by llzes** [comment]
Github isn't automatically closing this so closing manually again!

![Little things](http://i.imgur.com/Bksj0zw.jpg)
