### ISSUE TITLE
Need all backend endpoints to begin with /api/

### ISSUE THREAD

**Issue by wilm42** [thinkful-c11/devcupid#3]
Right now the api endpoints do not begin with /api/, some begin with /auth/ and others begin with something else. In order to properly route on the front end, we need some static handle on what gets routed to the server - we used regex to set this up using /api/. I could just change the endpoints myself, but it requires reconfiguring on github so that the redirect endpoint begins with /api/ on github's end as well.

**Comment by wilm42** [comment]
Current patch: On branch 'frontend-setup', I made it so that the regex looks for /auth/ to route to the server, otherwise it stays on the front end. This will need to be changed back to /api/ once fix for issue is implemented

**Comment by llzes** [comment]
Working on this right now, I'll update once I push `backend-dev` to `dev`!

**Comment by llzes** [comment]
Pull request completed! If there's something I need to fix let me know otherwise huzzah merge and close!

**Comment by tckastanek** [comment]
PR merged, so closing this issue.
