### ISSUE TITLE
Refactor models.js so that libraries are nested within languages.

### ISSUE THREAD

**Issue by tckastanek** [thinkful-c11/devcupid#7]
Refer to index.js in reducers for the formatting but we need to nest the libraries array within the languages key. It would look something like this, maybe: 
```js
languages: {
javascript: {
libraries: ['React', 'Redux'] 
}
}
```

**Comment by tckastanek** [comment]
```js
{
      text: 'What (if any) languages and libraries are you competent with?',
      type: 'checkbox-nested',
      key: 'languages',
      choices: [
        {
          language: 'JavaScript',
          libraries: ['React', 'Redux', 'Angular', 'Angular 2/4', 'Mongoose', 'JQuery', 'Vue', 'Node.js']
        },
        {
          language: 'HTML5',
          libraries: ['Pug']
        },
        {
          language: 'CSS3',
          libraries: ['SASS', 'LESS', 'Bootstrap', 'Foundation', 'Materialize', 'CSS Grid', 'Responsive Design', 'Mobile First']
        },
        {
          language: 'C',
          libraries: []
        },
        {
          language: 'C++',
          libraries: []
        },
        {
          language: 'C#',
          libraries: []
        },
        {
          language: 'Java',
          libraries: ['Swing', 'Spring Boot', 'Guava']
        },
        {
          language: 'PHP',
          libraries: ['Laravel', 'Dispatch']
        },
        {
          language: 'Python',
          libraries: ['Django', 'Flask']
        },
        {
          language: 'Perl',
          libraries: []
        },
        {
          language: 'Ruby',
          libraries: ['Rails', 'Sinatra']
        },
        {
          language: '.NET',
          libraries: []
        },
        {
          language: 'Go',
          libraries: []
        },
        {
          language: 'Rust',
          libraries: []
        },
        {
          language: 'Scala',
          libraries: []
        },
        {
          language: 'Clojure',
          libraries: ['Leiningen', 'Ring', 'Om']
        },
        {
          language: 'Swift/Objective-C',
          libraries: []
        },
        {
          language: 'Elm',
          libraries: []
        },
        {
          language: 'F#',
          libraries: []
        },
      ]
    },
```

**Comment by wilm42** [comment]
`` null
gitHub
:
__proto__
:
Object
loading
:
false
onboardingQuestions
:
(8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
profile
:
avatar_url
:
"img.jpg"
bio
:
"I'm a cool cool person"
blog
:
"blog.portfolio.com"
company
:
"Myself"
email
:
"William@email.com"
linked_in
:
"linkedin.com/profile"
location
:
"Atlanta"
name
:
"William"
personalTitle
:
"UI / UX Developer"
personal_website
:
"portfolio.com"
remoteOk
:
"True"
skills
:
languages
:
.NET
:
{_active: false}
C
:
{_active: false}
C#
:
{_active: false}
C++
:
{_active: false}
CSS3
:
{_active: true, SASS: true, LESS: false, Bootstrap: true, Foundation: false, …}
Clojure
:
{_active: false, Leiningen: false, Ring: false, Om: false}
Elm
:
{_active: false}
F#
:
{_active: false}
Go
:
{_active: false}
HTML5
:
{_active: true, Pug: false}
Java
:
{_active: false, Swing: false, Spring Boot: false, Guava: false}
JavaScript
:
Angular
:
false
Angular 2/4
:
false
JQuery
:
false
Mongoose
:
false
Node.js
:
true
React
:
true
Redux
:
true
Vue
:
false
_active
:
true
__proto__
:
Object
PHP
:
{_active: false, Laravel: false, Dispatch: false}
Perl
:
{_active: false}
Python
:
{_active: true, Django: true, Flask: false}
Ruby
:
{_active: false, Rails: false, Sinatra: false}
Rust
:
{_active: false}
Scala
:
{_active: false}
Swift/Objective-C
:
{_active: false}
emptyState
:
{}
__proto__
:
Object
libraries
:
[]
passions
:
Array(4)
0
:
"Ed Tech"
1
:
"UX"
2
:
"B2B"
3
:
"Internet of Things"
length
:
4
__proto__
:
Array(0)
roles
:
Array(6)
0
:
"Front-End Web Developer"
1
:
"Full-Stack Web Developer"
2
:
"Web Designer"
3
:
"UI Engineer"
4
:
"UX Engineer"
5
:
"Designer"
length
:
6
__proto__
:
Array(0)
softwareTools
:
Array(2)
0
:
"Sketch3"
1
:
"Adobe Illustrator"
length
:
2
__proto__
:
Array(0)
speciality
:
Array(5)
0
:
"Mobile"
1
:
"Blog"
2
:
"Web"
3
:
"UI"
4
:
"UX"
length
:
5
__proto__
:
Array(0)
__proto__
:
Object
twitter
:
"@profile"
__proto__
:
Object ``

**Comment by wilm42** [comment]
`null
gitHub
:
__proto__
:
Object
loading
:
false
onboardingQuestions
:
(8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
profile
:
avatar_url
:
"img.jpg"
bio
:
"I'm a cool cool person"
blog
:
"blog.portfolio.com"
company
:
"Myself"
email
:
"William@email.com"
linked_in
:
"linkedin.com/profile"
location
:
"Atlanta"
name
:
"William"
personalTitle
:
"UI / UX Developer"
personal_website
:
"portfolio.com"
remoteOk
:
"True"
skills
:
languages
:
.NET
:
{_active: false}
C
:
{_active: false}
C#
:
{_active: false}
C++
:
{_active: false}
CSS3
:
{_active: true, SASS: true, LESS: false, Bootstrap: true, Foundation: false, …}
Clojure
:
{_active: false, Leiningen: false, Ring: false, Om: false}
Elm
:
{_active: false}
F#
:
{_active: false}
Go
:
{_active: false}
HTML5
:
{_active: true, Pug: false}
Java
:
{_active: false, Swing: false, Spring Boot: false, Guava: false}
JavaScript
:
Angular
:
false
Angular 2/4
:
false
JQuery
:
false
Mongoose
:
false
Node.js
:
true
React
:
true
Redux
:
true
Vue
:
false
_active
:
true
__proto__
:
Object
PHP
:
{_active: false, Laravel: false, Dispatch: false}
Perl
:
{_active: false}
Python
:
{_active: true, Django: true, Flask: false}
Ruby
:
{_active: false, Rails: false, Sinatra: false}
Rust
:
{_active: false}
Scala
:
{_active: false}
Swift/Objective-C
:
{_active: false}
emptyState
:
{}
__proto__
:
Object
libraries
:
[]
passions
:
Array(4)
0
:
"Ed Tech"
1
:
"UX"
2
:
"B2B"
3
:
"Internet of Things"
length
:
4
__proto__
:
Array(0)
roles
:
Array(6)
0
:
"Front-End Web Developer"
1
:
"Full-Stack Web Developer"
2
:
"Web Designer"
3
:
"UI Engineer"
4
:
"UX Engineer"
5
:
"Designer"
length
:
6
__proto__
:
Array(0)
softwareTools
:
Array(2)
0
:
"Sketch3"
1
:
"Adobe Illustrator"
length
:
2
__proto__
:
Array(0)
speciality
:
Array(5)
0
:
"Mobile"
1
:
"Blog"
2
:
"Web"
3
:
"UI"
4
:
"UX"
length
:
5
__proto__
:
Array(0)
__proto__
:
Object
twitter
:
"@profile"
__proto__
:
Object`

**Comment by wilm42** [comment]
![screen shot 2017-08-24 at 10 24 42 am](https://user-images.githubusercontent.com/27362400/29671051-89450ae0-88b6-11e7-90cd-7e56d3671ae1.png)

**Comment by wilm42** [comment]
@Avizc , as discussed, here's a pretty version of the 'profile' portion of the state, as it exists on the front end. If we could make this match the back end, we'll be in good shape.

For some reason github won't hold formatting, I'll send it in slack.
