### ISSUE TITLE
Refactor Header comp to have access to the Router.

### ISSUE THREAD

**Issue by tckastanek** [thinkful-c11/devcupid#71]
Ran into this issue trying to link (with <Link />) to a Team view screen from the header. 

I'm going to hack around it for the moment by adding the link to the profile screen (which makes some UX sense as we don't want users to have the ability to go to other parts of the site before they have completed onboarding). However, we will want at some point to be able to move around the app using links in the header.

- [ ] Probably need to either factor the router out as a separate wrapper component for the entire app or factor the header in as a component that rendered by each major view.

- [ ] Need to figure out a way to disable or not render any links/actions in the header besides logging out while the user is onboarding.

**Comment by wilm42** [comment]
There's a neat part of the router API called withRouter that allows for this exact functionality. I can deal with this issue and I' can show you how it works, Thomas

**Comment by wilm42** [comment]
William got this going last week
